version: "3.9"
services: 
  restful-api:
    container_name: RESTful-API-Go-Endpoint
    depends_on:
      - database
    restart: always
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      MONGO_SERVICE_NAME: database
      API_PORT: 8081
    networks:
      rest_api_go_endpoint_network:
        aliases:
          - myapi
  
  database:
    container_name: MongoDB
    restart: always
    image: mongo:4.4.2
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - rest_api_go_endpoint_network
  
  nginx:
    container_name: Nginx-Proxy
    depends_on:
      - restful-api
    restart: always
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./Nginx:/var/log/nginx
    networks:
      - rest_api_go_endpoint_network

volumes:
  mongodata:
  Nginx:

networks:
  rest_api_go_endpoint_network:
    name: rest_api_go_endpoint_network